apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-docker
  namespace: howest-fastapi-ls # Replace with your namespace name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-docker
  template:
    metadata:
      labels:
        app: vue-docker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3d-k3s-default-agent-0
      containers:
        - name: vue-container
          image: spartanroyalty/docker-new-frontend:latest 
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: mariadb-fastapi-secret