apiVersion: v1
kind: Service
metadata:
  name: svc-vue-docker
  namespace: howest-fastapi-ls
spec:
  selector:
    app: vue-docker
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP